#!/usr/bin/env python

## Script to move robot joints into a position
## the position is not held unless physics engine is paused

import rospy, sys, os, time
import string
import warnings

from gazebo_msgs.srv import *
from gazebo_ros import gazebo_interface
from std_srvs.srv import Empty

def unpause(gazebo_namespace):
	rospy.wait_for_service(gazebo_namespace+'/unpause_physics')
	time.sleep(1)
	try:
		unpause_physics = rospy.ServiceProxy(gazebo_namespace+'/unpause_physics', Empty)
		resp = unpause_physics()
		return
	except rospy.ServiceException, e:
		print "Service call failed: %s"%e

if __name__ == "__main__":
	if len(sys.argv) < 2:
		sleep_time = 0.0
	else:
		print sys.argv[1]
		sleep_time = float(sys.argv[1])

	gazebo_namespace = "/gazebo"
	
	## Unpause physics
	rospy.wait_for_service('%s/unpause_physics'%(gazebo_namespace))
	try:
		success = unpause(gazebo_namespace)
		print "Physics Engine Running"
	except rospy.ServiceException, e:
		print "unpause physics service call failed: %s"%e